variables:
  NODE_VERSION: 18

stages:
  - build
  - publish

before_script:
  - npm ci

build:
  stage: build
  image: node:$NODE_VERSION
  only:
    - master
    - develop
    - merge_requests
  script:
    - npm run lint
    - npm run build
    - npm run test
    - npm audit --omit=dev

publish:
  stage: publish
  image: node:$NODE_VERSION
  only:
    - tags
  script:
    - npm run lint
    - npm run build
    - npm run test
    - npm audit --omit=dev
    - npm --no-git-tag-version version ${CI_COMMIT_TAG}
    - npm publish --access public --userconfig $NPM_RC
